image: php:8.0-fpm

pipelines:
  default:
    - step:
        services:
          - mysql
        name: 'Build and Test'
        script:
          - bash ./devops/build-server.sh
          - bash ./devops/build-project.sh
          - bash ./devops/run-tests.sh

definitions:
  services:
    mysql:
      image: mysql:8.0
      environment:
        MYSQL_DATABASE: 'homestead'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'homestead'
        MYSQL_PASSWORD: 'secret'
